version: "3.3"

services:
  blueprint_frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
  blueprint_backend:
    build: ./backend
    environment:
      - MONGODB_ADDR=mongodb://mongodb
    restart: always
    ports:
      - "6060:6060"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
